### ISSUE TITLE
'invalid argument type' when using plot_realization

### ISSUE THREAD

**Issue by CrunchyLettuce** [Nowosad/raceland#10]
Hi,

I'm getting this error for plot_realization:

`Error in !all.equal(dim(x)[c(1, 2)], dim(y)[c(1, 2)]) : 
  invalid argument type`

I was able to use this function without issues for a different dataset, but I'm not sure what about my new data could be causing it. The other functions I'm using (zones_to_raster, quantify_raceland and create_realizations) seem to be working perfectly well on the data. Do you have any idea?

Thanks

**Comment by Nowosad** [comment]
Hi @CrunchyLettuce, could you share your (minimal) code and data here or privately?

**Comment by CrunchyLettuce** [comment]
Sorry - figured out the (very dumb) problem. Thanks for responding anyway, and for the great package!
