### ISSUE TITLE
upcoming sf breaks raceland on CRAN

### ISSUE THREAD

**Issue by edzer** [Nowosad/raceland#5]
See
* https://www.r-spatial.org/r/2020/03/17/wkt.html
* https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

Changes in the `crs` object break tests and/or vignettes in raceland. Please update accordingly and submit to CRAN.

**Comment by Nowosad** [comment]
Related to https://github.com/rspatial/raster/issues/101.

**Comment by Nowosad** [comment]
It is temporarily fixed - https://cran.r-project.org/web/packages/raceland/index.html.
