### ISSUE TITLE
Misspelled function quantify_raceland

### ISSUE THREAD

**Issue by camille-s** [Nowosad/raceland#7]
It looks like the function to calculate metrics is misspelled in being exported: `quanfity_raceland` should be `quantify_raceland`, right?

**Comment by Nowosad** [comment]
Dear @camille-s - I somehow missed your issue. You are totally correct, thank you! I have fixed the issue in the development version of the package and plan to update the CRAN version next weekend. I also plan to update my blog post (https://nowosad.github.io/post/raceland-bp1/) soon.

**Comment by Nowosad** [comment]
New version is on CRAN now - https://cran.r-project.org/package=raceland.
