### ISSUE TITLE
Function not exported

### ISSUE THREAD

**Issue by JOEHDZ17** [Nowosad/raceland#8]
Hi, I am was using the Raceland code, and before I did not have this issue when calculating the realizations, densities, or metrics but recently I have been having this error message and cannot seem to have an output for the metrics. Here is the error message: 

Error in get_metrics(x = raster::as.matrix(x), w = raster::as.matrix(w),  : 
  Function not exported: C++ function with signature 'double(*rcpp_ent)(const Rcpp::NumericMatrix,std::string)' not found in comat.

Have any recommendations to solve this? Thank you.

**Comment by Nowosad** [comment]
Hi @JOEHDZ17. Two ideas:

1. Try to update the comat package - `install.packages("comat")`, next the raceland package `install.packages("raceland")`, restart your R session and try again.
2. If it does not help, could you prepare mi a tiny example of your data and code? I will try to help you then.

**Comment by Nowosad** [comment]
@JOEHDZ17 feel free to reopen the issue if the problem still occurs.
